---
title: "day-2"
author: "Aishwarya"
---

## Introduction

I am working with data summaries. First, mpg, then something else.

```{r}
#| label: setup
library(tidyverse)
library(mosaic)
library(ggformula)
library(kableExtra)
```

## Look at this mpg dataset

```{r}
glimpse(mpg)
```

```{r}
mpg
  head(10)
```

```{r}
inspect(mpg)
```

```{r}
skimr::skim(mpg)
```

```{r}
mpg_modified <- mpg %>%
  dplyr::mutate(
    cyl = as_factor(cyl),
    fl = as_factor(fl),
    drv = as_factor(drv),
    class = as_factor(class),
    trans = as_factor(trans)
  )
glimpse(mpg_modified)
```

```{r}
mpg_modified %>%
  group_by(cyl) %>%
  summarize(average_hwy = mean(hwy), count = n())
```

```{r}
mpg_modified %>%
  group_by(cyl, fl) %>%
  summarize(average_hwy = mean(hwy), count = n())
```

# Math Anxiety data set

We are working with Math anxiety data set, Nagesh and I.

```{r}
math_anxiety <- read_csv("../../data/MathAnxiety.csv")
math_anxiety
```

```{r}
math_anxiety %>% 
  head(10)
```

```{r}
glimpse(math_anxiety)
```

```{r}
inspect(math_anxiety)
```

```{r}
skimr::skim(math_anxiety)
```

```{r}
math_anxiety <- read_delim(file = "../../data/MathAnxiety.csv",delim =";")
```

```{r}
math_anxiety %>% 
  head(10)
```

```{r}
math_anxiety_modified <- math_anxiety %>% dplyr::mutate( 
  Age = Age/120, 
  Gender = as_factor(Gender),

) 
glimpse(math_anxiety_modified)
```

```{r}
inspect(math_anxiety)
```

```{r}
math_anxiety_modified %>%
  group_by(Gender) %>%
  summarize(average_AMAS = mean(AMAS, na.rm = TRUE),count = n())
```

```{r}
math_anxiety_modified %>%
  group_by(Gender) %>%
  summarize(average_RCMAS = mean(RCMAS, na.rm = TRUE),count = n())
```
