---
title: "blog-aish"
---

# day-3

## we are examining the taxi data set

```{r}
#| label: setup
library(tidyverse)
library(mosaic)
library(ggformula)
library(skimr)

```

```{r}
taxi <- read_csv("https://vincentarelbundock.github.io/Rdatasets/csv/modeldata/taxi.csv")
taxi
```

```{r}
glimpse(taxi)

```

```{r}
skim(taxi)

```

```{r}
inspect(taxi)
```

```{r}
taxi_modified <- taxi %>%
  mutate(
    dow = factor(dow,
      levels = c("Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"),
      labels = c("Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"),
      ordered = TRUE
    ),
    ##
    local = factor(local,
      levels = c("no", "yes"),
      labels = c("no", "yes"),
      ordered = TRUE
    ),
    ##
    month = factor(month,
      levels = c("Jan", "Feb", "Mar", "Apr"),
      labels = c("Jan", "Feb", "Mar", "Apr"),
      ordered = TRUE
    )
  )
taxi_modified %>% glimpse()
```

```{r}
## Set graph theme

gf_bar(~tip, data = taxi_modified) %>%
  gf_labs(title = "Plot 1A: Counts of Tips")
```

```{r}
taxi_modified %>%
  gf_bar(~tip,
    fill = ~local,
  ) %>%
  gf_labs(title = "Plot 2A: Bar Chart")
```

```{r}
taxi_modified %>%
  gf_bar(~tip,
    fill = ~local,
    position = "stack"
  ) %>%
  gf_labs(title = "Plot 2A: Stacked Bar Chart")
```

```{r}
taxi_modified %>%
  gf_bar(~tip,
    fill = ~local,
    position = "dodge"
  ) %>%
  gf_labs(title = "Plot 2A: Dodged Bar Chart")
```

```{r}
taxi_modified %>%
  gf_bar(~tip,
    fill = ~local,
    position = "fill"
  ) %>%
  gf_labs(title = "Plot 2A: Dodged Bar Chart")
```

```{r}
taxi_modified %>%
  gf_bar(~company,
    fill = ~tip,
    position = "fill"
  ) %>%
  gf_labs(
    title = "Plot 2D: Filled Bar Chart",
    subtitle = "Shows Per group differences in Proportions!"
  )
```

```{r}
taxi_modified %>%
  gf_bar(~hour,
    fill = ~tip,
  ) %>%
  gf_labs(
    title = "Plot B: Counts of Tips by Hour"
  )
```

```{r}
taxi_modified %>%
  gf_bar(~dow,
    fill = ~tip,
  ) %>%
  gf_labs(
    title = "Plot C: Counts of Tips by Day of Week"
  )
```

```{r}
taxi_modified %>% 
  gf_bar(~month,
    fill = ~tip
  ) %>% 
  gf_labs( title = "Plot D: Counts of Tips by Month")
```

```{r}
taxi_modified %>% 
  gf_bar(~month | dow,
    fill = ~tip
  ) %>% 
  gf_labs( title = "Plot D: Counts of Tips by day of week and month")
```

```{r}
taxi_modified %>% 
  gf_bar(~dow | hour,
    fill = ~tip
  ) %>% 
  gf_labs( 
    title = "Plot F: Counts of Tips by Hour and Day of Week",
    subtitle = "Is this plot arrangement easy to grasp?"
    )
```

```{r}
taxi_modified %>% 
  gf_bar(~dow | hour,
    fill = ~tip,
    position = "fill"
  ) %>% 
  gf_labs( 
    title = "Plot F: Counts of Tips by Hour and Day of Week",
    subtitle = "Is this plot arrangement easy to grasp?"
    )
```
